spring.datasource.url=jdbc:postgresql://localhost:5432/AgriSathi
spring.datasource.password=1643
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.username=postgres
llm.api.key=b65bf930-1fb0-4ad1-84a8-2e0f6470d8dd
llm.api.url=https://api.sambanova.ai/v1/chat/completions

weather.api.key=f8a622574d8d6549b334da93b297f6c7
weather.api.base-url=https://api.openweathermap.org/data/2.5/weather